import {NextResponse} from 'next/server';
import {getPgPool} from '../../../lib/pg-database';

type Session={id:string;role:string;title:string;subjectKey:string;customerKey:string;routeId:string;orderId:string;invoiceId:string;appointmentId:string;status:string;metadata:Record<string,any>;createdAt:string;updatedAt:string;messages?:Message[]};
type Message={id:string;sessionId:string;role:string;content:string;metadata:Record<string,any>;createdAt:string};
const memory=globalThis as typeof globalThis&{ccpAiSessions?:Session[];ccpAiMessages?:Message[]};
function sessions(){if(!memory.ccpAiSessions)memory.ccpAiSessions=[];return memory.ccpAiSessions}
function messages(){if(!memory.ccpAiMessages)memory.ccpAiMessages=[];return memory.ccpAiMessages}
function accessRole(request:Request){const cookie=request.headers.get('cookie')||'';return cookie.match(/(?:^|; )ccp_access=([^;]+)/)?.[1]||''}
function canRead(role:string,requested:string){if(requested==='customer')return true;if(role==='owner')return true;return role==='driver'&&requested==='driver'}
function clean(v:any){return String(v||'').trim()}
function now(){return new Date().toISOString()}
function id(prefix:string){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
function json(v:any){return JSON.stringify(v&&typeof v==='object'?v:{})}
function sessionFrom(input:any):Session{const t=now();return {id:clean(input?.id)||id('CHAT'),role:clean(input?.role)||'customer',title:clean(input?.title)||'New chat',subjectKey:clean(input?.subjectKey)||'general',customerKey:clean(input?.customerKey),routeId:clean(input?.routeId),orderId:clean(input?.orderId),invoiceId:clean(input?.invoiceId),appointmentId:clean(input?.appointmentId),status:clean(input?.status)||'open',metadata:input?.metadata&&typeof input.metadata==='object'?input.metadata:{},createdAt:clean(input?.createdAt)||t,updatedAt:t}}
function messageFrom(input:any,sessionId:string):Message{return {id:clean(input?.id)||id('MSG'),sessionId,role:clean(input?.role)||'user',content:clean(input?.content),metadata:input?.metadata&&typeof input.metadata==='object'?input.metadata:{},createdAt:clean(input?.createdAt)||now()}}
function mapSession(row:any):Session{return {id:row.id,role:row.role,title:row.title,subjectKey:row.subject_key||'general',customerKey:row.customer_key||'',routeId:row.route_id||'',orderId:row.order_id||'',invoiceId:row.invoice_id||'',appointmentId:row.appointment_id||'',status:row.status,metadata:row.metadata||{},createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()}}
function mapMessage(row:any):Message{return {id:row.id,sessionId:row.session_id,role:row.role,content:row.content,metadata:row.metadata||{},createdAt:new Date(row.created_at).toISOString()}}
async function ensure(pool:any){await pool.query("create table if not exists ai_chat_sessions (id text primary key,role text not null default 'customer',title text not null default 'New chat',subject_key text default 'general',customer_key text default '',route_id text default '',order_id text default '',invoice_id text default '',appointment_id text default '',status text not null default 'open',metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now())");await pool.query("create table if not exists ai_chat_messages (id text primary key,session_id text not null references ai_chat_sessions(id) on delete cascade,role text not null,content text not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now())");await pool.query('create index if not exists idx_ai_chat_sessions_role on ai_chat_sessions(role)');await pool.query('create index if not exists idx_ai_chat_messages_session_id on ai_chat_messages(session_id)')}

export async function GET(request:Request){const url=new URL(request.url);const requested=url.searchParams.get('role')||'customer';const role=accessRole(request);if(!canRead(role,requested))return NextResponse.json({ok:false,message:'Role access required'},{status:401});const sessionId=url.searchParams.get('sessionId')||'';const pool=getPgPool();if(pool){try{await ensure(pool);const sessionRows=await pool.query(sessionId?'select * from ai_chat_sessions where id=$1 limit 1':'select * from ai_chat_sessions where role=$1 order by updated_at desc limit 100',sessionId?[sessionId]:[requested]);const out=sessionRows.rows.map(mapSession);if(sessionId&&out[0]){const msgRows=await pool.query('select * from ai_chat_messages where session_id=$1 order by created_at asc',[sessionId]);out[0].messages=msgRows.rows.map(mapMessage)}return NextResponse.json({ok:true,storage:'postgres',sessions:out})}catch(error:any){return NextResponse.json({ok:false,message:error?.message||'AI memory unavailable'},{status:500})}}const out=sessions().filter(s=>sessionId?s.id===sessionId:s.role===requested).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,100);if(sessionId&&out[0])out[0]={...out[0],messages:messages().filter(m=>m.sessionId===sessionId).sort((a,b)=>a.createdAt.localeCompare(b.createdAt))};return NextResponse.json({ok:true,storage:'memory',sessions:out})}

export async function POST(request:Request){const role=accessRole(request);const input=await request.json();const action=clean(input?.action)||'save-session';const session=sessionFrom(input?.session||input);if(!canRead(role,session.role))return NextResponse.json({ok:false,message:'Role access required'},{status:401});const nextMessages=(input?.messages||[]).map((m:any)=>messageFrom(m,session.id)).filter((m:Message)=>m.content);const pool=getPgPool();if(pool){try{await ensure(pool);await pool.query('insert into ai_chat_sessions (id,role,title,subject_key,customer_key,route_id,order_id,invoice_id,appointment_id,status,metadata,created_at,updated_at) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13) on conflict (id) do update set title=excluded.title,subject_key=excluded.subject_key,customer_key=excluded.customer_key,route_id=excluded.route_id,order_id=excluded.order_id,invoice_id=excluded.invoice_id,appointment_id=excluded.appointment_id,status=excluded.status,metadata=excluded.metadata,updated_at=excluded.updated_at',[session.id,session.role,session.title,session.subjectKey,session.customerKey,session.routeId,session.orderId,session.invoiceId,session.appointmentId,session.status,json(session.metadata),session.createdAt,session.updatedAt]);for(const m of nextMessages){await pool.query('insert into ai_chat_messages (id,session_id,role,content,metadata,created_at) values ($1,$2,$3,$4,$5::jsonb,$6) on conflict (id) do nothing',[m.id,m.sessionId,m.role,m.content,json(m.metadata),m.createdAt])}return NextResponse.json({ok:true,storage:'postgres',session,messages:nextMessages,action})}catch(error:any){return NextResponse.json({ok:false,message:error?.message||'AI memory save failed'},{status:500})}}const list=sessions();const i=list.findIndex(s=>s.id===session.id);if(i>=0)list[i]=session;else list.unshift(session);messages().push(...nextMessages);return NextResponse.json({ok:true,storage:'memory',session,messages:nextMessages,action})}
