import {NextResponse} from 'next/server';
import {getPgPool} from '../../../lib/pg-database';
import {withContextTrust,type ContextRecordSource} from '../../../lib/context-trust';

type BoardMessage={id:string;audience:'owner'|'driver'|'customer-approved';createdBy:string;subject:string;body:string;status:'open'|'review'|'closed';priority:'low'|'normal'|'high'|'urgent';routeId:string;orderId:string;source:string;aiApproved:boolean;metadata:Record<string,any>;createdAt:string;updatedAt:string;closedAt?:string;contextTrust?:any};
const memory=globalThis as typeof globalThis&{ccpInternalBoard?:BoardMessage[]};
function mem(){if(!memory.ccpInternalBoard)memory.ccpInternalBoard=[];return memory.ccpInternalBoard}
function accessRole(request:Request){const cookie=request.headers.get('cookie')||'';return cookie.match(/(?:^|; )ccp_access=([^;]+)/)?.[1]||''}
function authorized(role:string){return role==='owner'||role==='driver'}
function requiresPostgres(){return process.env.NODE_ENV==='production'||process.env.CCP_REQUIRE_POSTGRES==='true'}
function clean(v:any){return String(v||'').trim()}
function pick<T extends string>(v:any,allowed:T[],fallback:T):T{const x=clean(v) as T;return allowed.includes(x)?x:fallback}
function meta(input:any){return {...(input?.metadata&&typeof input.metadata==='object'?input.metadata:{}),customerEmail:clean(input?.customerEmail).toLowerCase(),customerName:clean(input?.customerName)}}
function trustSource(record:BoardMessage,storage:ContextRecordSource):ContextRecordSource{if(record.audience==='customer-approved')return 'owner-override';if(record.createdBy==='driver')return 'driver-note';return storage}
function trustReason(record:BoardMessage,storage:ContextRecordSource){if(record.audience==='customer-approved')return 'Owner-approved board record.';if(record.createdBy==='driver')return 'Driver note pending owner review.';return storage==='postgres'?'Official internal board record from PostgreSQL.':'Working internal board memory.'}
function label(record:BoardMessage,storage:ContextRecordSource){return record.contextTrust?record:withContextTrust(record,trustSource(record,storage),{reason:trustReason(record,storage)})}
function labelRows(rows:BoardMessage[],storage:ContextRecordSource){return (rows||[]).map(row=>label(row,storage))}
function map(row:any):BoardMessage{return {id:row.id,audience:row.audience,createdBy:row.created_by,subject:row.subject,body:row.body,status:row.status,priority:row.priority,routeId:row.route_id||'',orderId:row.order_id||'',source:row.source||'manual',aiApproved:Boolean(row.ai_approved),metadata:row.metadata||{},createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString(),closedAt:row.closed_at?new Date(row.closed_at).toISOString():undefined}}
function make(input:any,role:string):BoardMessage{const now=new Date().toISOString();const audience=pick(input?.audience,['owner','driver','customer-approved'],'owner');const status=pick(input?.status,['open','review','closed'],'open');return {id:clean(input?.id)||`BOARD-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,audience,createdBy:role,subject:clean(input?.subject)||'Internal note',body:clean(input?.body),status,priority:pick(input?.priority,['low','normal','high','urgent'],'normal'),routeId:clean(input?.routeId),orderId:clean(input?.orderId),source:clean(input?.source)||'manual',aiApproved:Boolean(input?.aiApproved)||audience==='customer-approved',metadata:meta(input),createdAt:clean(input?.createdAt)||now,updatedAt:now,closedAt:status==='closed'?now:undefined}}
async function ensureBoard(pool:any){await pool.query("create table if not exists internal_board_messages (id text primary key,audience text not null default 'owner',created_by text not null default 'system',subject text not null,body text not null,status text not null default 'open',priority text not null default 'normal',route_id text default '',order_id text default '',source text default 'manual',ai_approved boolean not null default false,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),closed_at timestamptz)");await pool.query('create index if not exists idx_internal_board_messages_audience on internal_board_messages(audience)');await pool.query('create index if not exists idx_internal_board_messages_status on internal_board_messages(status)')}

export async function GET(request:Request){const role=accessRole(request);if(!authorized(role))return NextResponse.json({ok:false,message:'Internal access required'},{status:401});const pool=getPgPool();if(pool){try{await ensureBoard(pool);const result=await pool.query('select * from internal_board_messages order by created_at desc limit 200');return NextResponse.json({ok:true,storage:'postgres',records:labelRows(result.rows.map(map),'postgres')})}catch(error:any){if(requiresPostgres())return NextResponse.json({ok:false,message:error?.message||'Internal board unavailable'},{status:500})}}return NextResponse.json({ok:true,storage:'memory',records:labelRows(mem(),'memory')})}

export async function POST(request:Request){const role=accessRole(request);if(!authorized(role))return NextResponse.json({ok:false,message:'Internal access required'},{status:401});const record=make(await request.json(),role);if(role==='driver'&&record.audience==='customer-approved')return NextResponse.json({ok:false,message:'Owner approval required for customer-facing board messages.'},{status:403});const pool=getPgPool();if(pool){try{await ensureBoard(pool);await pool.query('insert into internal_board_messages (id,audience,created_by,subject,body,status,priority,route_id,order_id,source,ai_approved,metadata,created_at,updated_at,closed_at) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13,$14,$15) on conflict (id) do update set audience=excluded.audience,subject=excluded.subject,body=excluded.body,status=excluded.status,priority=excluded.priority,route_id=excluded.route_id,order_id=excluded.order_id,source=excluded.source,ai_approved=excluded.ai_approved,metadata=excluded.metadata,updated_at=excluded.updated_at,closed_at=excluded.closed_at',[record.id,record.audience,record.createdBy,record.subject,record.body,record.status,record.priority,record.routeId,record.orderId,record.source,record.aiApproved,JSON.stringify(record.metadata),record.createdAt,record.updatedAt,record.closedAt||null]);return NextResponse.json({ok:true,storage:'postgres',record:label(record,'postgres')})}catch(error:any){if(requiresPostgres())return NextResponse.json({ok:false,message:error?.message||'Internal board save failed'},{status:500})}}
const list=mem();const i=list.findIndex(m=>m.id===record.id);if(i>=0)list[i]=record;else list.unshift(record);return NextResponse.json({ok:true,storage:'memory',record:label(record,'memory')})}
