import { NextResponse } from 'next/server';
import { getPgPool } from '../../../../lib/pg-database';

const memory=globalThis as typeof globalThis&{ccpProfiles?:any[]};
function mem(){if(!memory.ccpProfiles)memory.ccpProfiles=[];return memory.ccpProfiles}
function role(request:Request){const c=request.headers.get('cookie')||'';return c.match(/(?:^|; )ccp_access=([^;]+)/)?.[1]||''}
function dept(v:any){const x=String(v||'support');return ['sales','billing','delivery','support','owner'].includes(x)?x:'support'}
function base(r:string){const d=dept(r==='owner'?'owner':'delivery');return {id:`${r}-default`,role:r,displayName:r==='owner'?'Owner':'Driver',preferredSenderEmail:'',defaultDepartment:d,backupRoute:`aifreedomtrust+ccp-${d}@gmail.com`,messagePermissions:r==='owner'?['review','approve','export']:['route','message','turn-in'],setupComplete:false,updatedAt:new Date().toISOString()}}
function clean(input:any,r:string){const b=base(r);const d=dept(input?.defaultDepartment||b.defaultDepartment);return {...b,displayName:String(input?.displayName||b.displayName).trim(),preferredSenderEmail:String(input?.preferredSenderEmail||'').trim(),defaultDepartment:d,backupRoute:String(input?.backupRoute||`aifreedomtrust+ccp-${d}@gmail.com`).trim(),messagePermissions:Array.isArray(input?.messagePermissions)?input.messagePermissions.map(String):b.messagePermissions,setupComplete:Boolean(input?.setupComplete),updatedAt:new Date().toISOString()}}
function map(row:any){return {id:row.id,role:row.role,displayName:row.display_name,preferredSenderEmail:row.preferred_sender_email||'',defaultDepartment:row.default_department,backupRoute:row.backup_route||'',messagePermissions:row.message_permissions||[],setupComplete:Boolean(row.setup_complete),updatedAt:new Date(row.updated_at).toISOString()}}

export async function GET(request:Request){const r=role(request);if(r!=='owner'&&r!=='driver')return NextResponse.json({ok:false},{status:401});const id=`${r}-default`;const pool=getPgPool();if(!pool)return NextResponse.json({ok:true,storage:'memory',profile:mem().find(p=>p.id===id)||base(r)});const result=await pool.query('select * from ccp_user_profiles where id=$1 limit 1',[id]);return NextResponse.json({ok:true,storage:'postgres',profile:result.rows[0]?map(result.rows[0]):base(r)})}
export async function POST(request:Request){const r=role(request);if(r!=='owner'&&r!=='driver')return NextResponse.json({ok:false},{status:401});const profile=clean(await request.json(),r);const pool=getPgPool();if(!pool){const list=mem();const i=list.findIndex(p=>p.id===profile.id);if(i>=0)list[i]=profile;else list.unshift(profile);return NextResponse.json({ok:true,storage:'memory',profile})}await pool.query('insert into ccp_user_profiles (id,role,display_name,preferred_sender_email,default_department,backup_route,message_permissions,setup_complete,updated_at) values ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,now()) on conflict (id) do update set display_name=excluded.display_name,preferred_sender_email=excluded.preferred_sender_email,default_department=excluded.default_department,backup_route=excluded.backup_route,message_permissions=excluded.message_permissions,setup_complete=excluded.setup_complete,updated_at=now()',[profile.id,profile.role,profile.displayName,profile.preferredSenderEmail,profile.defaultDepartment,profile.backupRoute,JSON.stringify(profile.messagePermissions),profile.setupComplete]);return NextResponse.json({ok:true,storage:'postgres',profile})}
