'use client';
import {useMemo,useState} from 'react';
import LocalAIConcierge from './LocalAIConcierge';

type Props={snapshot:Record<string,any>};
function money(value:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value||0)}
function trainingMessages(record:any){return [{role:'system',content:'You are Capital City Provisions owner AI. Use owner-approved operational memory only.'},{role:'user',content:String(record.input||record.type||'Review this operating event.')},{role:'assistant',content:String(record.output||record.summary||'No output recorded.')}];}
function downloadJsonl(records:any[]){const rows=records.map(record=>JSON.stringify({messages:trainingMessages(record),source:'owner-reviewed-database-console',type:record.type||'training',approvedAt:new Date().toISOString()})).join('\n')+'\n';const blob=new Blob([rows],{type:'application/x-ndjson'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='ccp-owner-approved-training.jsonl';link.click();URL.revokeObjectURL(url)}
function downloadFile(name:string,type:string,content:string){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
function csvEscape(value:any){return `"${String(value??'').replace(/"/g,'""')}"`}
function exportOrdersCsv(orders:any[]){const headers=['id','customerName','phone','zip','routeId','box','status','fulfillment','value','deliveryDate','deliveryWindow','notes'];const rows=[headers.join(','),...orders.map(order=>headers.map(header=>csvEscape(order[header])).join(','))];downloadFile('ccp-orders.csv','text/csv',rows.join('\n')+'\n')}
function exportBackup(data:any){downloadFile(`ccp-local-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json',JSON.stringify(data,null,2))}

export default function DatabaseOpsConsole({snapshot}:Props){
  const [orders,setOrders]=useState<any[]>(snapshot.orderLifecycle||[]);
  const [report,setReport]=useState<any>(snapshot.ownerReport||{});
  const [trainingRecords,setTrainingRecords]=useState<any[]>(snapshot.trainingDataset?.records||[]);
  const [approvedTraining,setApprovedTraining]=useState<any[]>([]);
  const [newOrder,setNewOrder]=useState({customerName:'',phone:'',zip:'',routeId:'route-intake',box:'Family Box',value:'500',deliveryDate:'TBD',deliveryWindow:'TBD',products:'beef, chicken',notes:''});
  const [update,setUpdate]=useState({orderId:orders[0]?.id||'',routeId:orders[0]?.routeId||'',driver:'Driver',status:'out-for-delivery',fulfillment:'pending',partialReason:'',restockIssue:'',substitutions:'',customerNotes:'',fuelStart:'',fuelEnd:'',milesDriven:''});
  const [notice,setNotice]=useState('');
  const mode='live';
  const hasOrders=orders.length>0;
  const aiContext=useMemo(()=>({role:'owner',database:{mode,orders,report,learning:{records:trainingRecords,approved:approvedTraining},knowledge:snapshot.aiKnowledge},permissions:{owner:['orders','driver updates','restock','profit loss','route efficiency','training dataset','repo knowledge']}}),[orders,report,trainingRecords,approvedTraining,snapshot.aiKnowledge]);

  async function submitUpdate(e:React.FormEvent){
    e.preventDefault();
    if(!update.orderId){setNotice('Create or receive an order before submitting a driver update.');return}
    setNotice('Saving driver update...');
    const response=await fetch('/api/db/driver-update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(update)});
    const result=await response.json();
    if(result.ok){setOrders(current=>current.map(order=>order.id===result.lifecycle?.id?result.lifecycle:order));setNotice(`Updated ${result.update.orderId}: ${result.update.status}, ${result.update.fulfillment}, efficiency ${result.update.routeEfficiency}.`);refreshReport()}else setNotice('Driver update failed.');
  }
  async function refreshReport(){const response=await fetch('/api/db/reports?training=1');const result=await response.json();if(result.ok){if(result.report)setReport(result.report);if(result.trainingDataset?.records)setTrainingRecords(result.trainingDataset.records)}}
  function approveRecord(record:any){setApprovedTraining(current=>current.some(item=>item===record)?current:[record,...current]);setNotice('Training example approved for local export. Nothing was sent to an external API.');}
  async function submitOrder(e:React.FormEvent){
    e.preventDefault();
    setNotice('Creating order...');
    const products=newOrder.products.split(',').map(product=>product.trim()).filter(Boolean).map((product,index)=>({sku:`OWNER-${index+1}`,name:product,qty:1,unit:'preference',fulfilled:0}));
    const response=await fetch('/api/db/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...newOrder,value:Number(newOrder.value||0),products,status:'ordered',fulfillment:'pending'})});
    const result=await response.json();
    if(result.ok){setOrders(current=>[result.lifecycle||result.order,...current]);setUpdate(current=>({...current,orderId:result.order.id,routeId:result.order.routeId}));setNotice(`Created ${result.order.id} for ${result.order.customerName}.`);refreshReport();return}
    setNotice('Order create failed.');
  }
  function saveLocalBackup(){const backup={savedAt:new Date().toISOString(),mode,orders,report,trainingRecords,approvedTraining,aiKnowledge:snapshot.aiKnowledge};localStorage.setItem('ccp_owner_local_backup',JSON.stringify(backup));exportBackup(backup);setNotice('Local backup saved on this device and exported as JSON.');}

  return <main className="site page-flow db-console">
    <section className="page-hero poster-frame"><div><p className="eyebrow">System Database - live</p><h1>Order lifecycle command center.</h1><p className="lead">Track real orders from first customer input through delivery, partial fulfillment, restock issues, driver notes, fuel efficiency, owner reports, and AI learning records.</p><div className="actions"><a href="#create-order">Create Order</a><a href="#driver-update">Update Delivery</a><a href="#owner-report">Owner Report</a><a href="#training-review">Review Training</a></div></div><img src="/images/capital-city-hero.png" alt="Capital City Provisions database system"/></section>
    <section className="section ops-grid"><div><LocalAIConcierge role="owner" context={aiContext}/></div><aside className="ops-side"><p className="eyebrow">Owner Report</p><h2>{report.date}</h2><div className="metric-list"><span>Mode <b>live</b></span><span>Revenue <b>{money(report.revenue)}</b></span><span>Cost <b>{money(report.estimatedCost)}</b></span><span>Profit <b>{money(report.estimatedProfit)}</b></span><span>Margin <b>{report.margin||0}%</b></span><span>Restock Issues <b>{report.restockIssues||0}</b></span><span>Training <b>{trainingRecords.length}</b></span><span>Approved <b>{approvedTraining.length}</b></span></div></aside></section>
    <section className="section" id="create-order"><p className="eyebrow">Owner Intake</p><h2>Create an order record.</h2><form onSubmit={submitOrder} className="db-form marble"><input value={newOrder.customerName} onChange={e=>setNewOrder({...newOrder,customerName:e.target.value})} placeholder="Customer name"/><input value={newOrder.phone} onChange={e=>setNewOrder({...newOrder,phone:e.target.value})} placeholder="Phone"/><input value={newOrder.zip} onChange={e=>setNewOrder({...newOrder,zip:e.target.value})} placeholder="ZIP"/><input value={newOrder.routeId} onChange={e=>setNewOrder({...newOrder,routeId:e.target.value})} placeholder="Route ID"/><input value={newOrder.box} onChange={e=>setNewOrder({...newOrder,box:e.target.value})} placeholder="Box"/><input value={newOrder.value} onChange={e=>setNewOrder({...newOrder,value:e.target.value})} placeholder="Value"/><input value={newOrder.deliveryDate} onChange={e=>setNewOrder({...newOrder,deliveryDate:e.target.value})} placeholder="Delivery date"/><input value={newOrder.deliveryWindow} onChange={e=>setNewOrder({...newOrder,deliveryWindow:e.target.value})} placeholder="Delivery window"/><input value={newOrder.products} onChange={e=>setNewOrder({...newOrder,products:e.target.value})} placeholder="Products, comma separated"/><textarea value={newOrder.notes} onChange={e=>setNewOrder({...newOrder,notes:e.target.value})} placeholder="Order notes"/><button type="submit">Create Order</button></form></section>
    <section className="section"><p className="eyebrow">Order Lifecycle</p><h2>Customer input to delivered.</h2><div className="training-actions"><button className="ops-button" onClick={()=>exportOrdersCsv(orders)} disabled={!orders.length}>Export Orders CSV</button><button className="ops-button ghost" onClick={saveLocalBackup}>Save Local Backup</button></div>{hasOrders?<div className="ops-table"><table><thead><tr><th>Order</th><th>Customer</th><th>Route</th><th>Status</th><th>Fulfillment</th><th>Delivery</th><th>Margin</th><th>Issues</th></tr></thead><tbody>{orders.map(order=><tr key={order.id}><td>{order.id}</td><td>{order.customerName}</td><td>{order.routeId}</td><td>{order.status}</td><td>{order.fulfillment}</td><td>{order.deliveryDate} {order.deliveryWindow}</td><td>{money(order.marginEstimate)}</td><td>{(order.restockIssues||[]).length}</td></tr>)}</tbody></table></div>:<article className="marble"><h3>Live database is empty.</h3><p>That is correct. Real records should appear only after successful customer ordering, order placement, driver updates, fulfillment, delivery, or restock events.</p></article>}</section>
    <section className="section" id="driver-update"><p className="eyebrow">Driver Update</p><h2>Delivery, fulfillment, restock, and fuel notes.</h2><form onSubmit={submitUpdate} className="db-form marble"><select value={update.orderId} onChange={e=>{const order=orders.find(o=>o.id===e.target.value);setUpdate({...update,orderId:e.target.value,routeId:order?.routeId||update.routeId})}}><option value="">Select order</option>{orders.map(order=><option key={order.id} value={order.id}>{order.id} - {order.customerName}</option>)}</select><input value={update.driver} onChange={e=>setUpdate({...update,driver:e.target.value})} placeholder="Driver"/><select value={update.status} onChange={e=>setUpdate({...update,status:e.target.value})}><option>out-for-delivery</option><option>delivered</option><option>partially-fulfilled</option><option>issue</option><option>restock-needed</option></select><select value={update.fulfillment} onChange={e=>setUpdate({...update,fulfillment:e.target.value})}><option>pending</option><option>packed</option><option>fulfilled</option><option>partial</option><option>restock-blocked</option><option>substituted</option></select><input value={update.fuelStart} onChange={e=>setUpdate({...update,fuelStart:e.target.value})} placeholder="Fuel start gallons"/><input value={update.fuelEnd} onChange={e=>setUpdate({...update,fuelEnd:e.target.value})} placeholder="Fuel end gallons"/><input value={update.milesDriven} onChange={e=>setUpdate({...update,milesDriven:e.target.value})} placeholder="Miles driven"/><input value={update.restockIssue} onChange={e=>setUpdate({...update,restockIssue:e.target.value})} placeholder="Restock issue"/><textarea value={update.partialReason} onChange={e=>setUpdate({...update,partialReason:e.target.value})} placeholder="Partial fulfillment reason"/><textarea value={update.substitutions} onChange={e=>setUpdate({...update,substitutions:e.target.value})} placeholder="Substitutions"/><textarea value={update.customerNotes} onChange={e=>setUpdate({...update,customerNotes:e.target.value})} placeholder="Customer or delivery notes"/><button type="submit">Save Driver Update</button></form>{notice&&<p>{notice}</p>}</section>
    <section className="section" id="training-review"><p className="eyebrow">AI Training Review</p><h2>Approve only the records you want the local model to learn from.</h2><div className="training-actions"><button className="ops-button" onClick={()=>downloadJsonl(approvedTraining)} disabled={!approvedTraining.length}>Export Approved JSONL</button><button className="ops-button ghost" onClick={refreshReport}>Refresh Training Records</button></div><div className="route-list ops-cards training-cards">{trainingRecords.length?trainingRecords.slice(0,12).map((record,index)=><article key={`${record.type}-${index}`}><p className="eyebrow">{record.type||'record'}</p><h3>{record.input||record.eventType||'Training signal'}</h3><p>{record.output||record.summary}</p><button onClick={()=>approveRecord(record)}>{approvedTraining.includes(record)?'Approved':'Approve For Local Training'}</button></article>):<article><h3>No training records yet.</h3><p>Live records appear after customer intake, order creation, driver updates, restock issues, and route learning events.</p></article>}</div></section>
    <section className="section" id="owner-report"><p className="eyebrow">Owner Report</p><h2>Profit, loss, restock, and next action.</h2><div className="route-list ops-cards"><article><h3>Owner Actions</h3>{(report.ownerActions||[]).map((item:string)=><p key={item}>{item}</p>)}</article><article><h3>Future Restock</h3>{(report.futureRestock||[]).length?(report.futureRestock||[]).map((item:any)=><p key={`${item.product}-${item.reason}`}><strong>{item.product}:</strong> {item.needed} needed. {item.reason}</p>):<p>No restock needs recorded yet.</p>}</article><article><h3>AI Learning Notes</h3>{(report.learningNotes||[]).length?(report.learningNotes||[]).map((item:string)=><p key={item}>{item}</p>):<p>No learning records yet. They begin after real customer and driver events.</p>}</article></div></section>
    <section className="section"><p className="eyebrow">Route Efficiency</p><h2>Fuel-aware delivery intelligence.</h2><div className="route-list ops-cards">{(report.routeEfficiency||[]).map((route:any)=><article key={route.routeId}><h3>{route.route}</h3><p>Efficiency: {route.efficiency}</p><p>Miles: {route.milesDriven}</p><p>Fuel used: {route.fuelUsed}</p><strong>Estimated route profit: {money(route.profit)}</strong></article>)}</div></section>
    <style>{`.ops-grid{display:grid;grid-template-columns:1fr 320px;gap:20px}.ops-side{border:1px solid rgba(255,200,87,.5);border-radius:22px;padding:20px;background:#080605;height:max-content}.metric-list{display:grid;gap:10px}.metric-list span{display:flex;justify-content:space-between;border-bottom:1px solid #b8892d55;padding-bottom:8px;color:#ded2bd}.metric-list b{color:#f8e7b0}.ops-table{overflow:auto;border:1px solid #b8892d66;border-radius:18px}.ops-table table{width:100%;border-collapse:collapse;min-width:900px;background:#050403}.ops-table th,.ops-table td{border-bottom:1px solid #b8892d44;padding:12px;text-align:left}.ops-table th{color:#f8e7b0}.db-form{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.db-form input,.db-form textarea,.db-form select{min-width:0;border:1px solid #b8892d;background:#050403;color:#fff7ed;border-radius:14px;padding:12px;font:inherit}.db-form textarea{grid-column:span 3;min-height:84px}.db-form button,.ops-button{border:1px solid #f8e7b0;background:linear-gradient(135deg,#facc15,#a16207);color:#160b04;border-radius:999px;padding:12px 16px;font-weight:900}.ops-button.ghost{background:#080605;color:#f8e7b0}.training-actions{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:14px}.training-cards button{border:1px solid #d4af37;background:#080605;color:#f8e7b0;border-radius:999px;padding:10px 12px;font-weight:900}@media(max-width:900px){.ops-grid{grid-template-columns:1fr}.db-form{grid-template-columns:1fr}.db-form textarea{grid-column:auto}}`}</style>
  </main>
}
