'use client';
import {useEffect,useMemo,useState} from 'react';

type Msg={id:string;direction:string;customerEmail:string;customerName?:string;subject:string;body:string;status:string;stage?:string;source?:string;provider?:string;createdAt:string;sentAt?:string;receivedAt?:string;metadata?:Record<string,any>};

function risk(m:Msg){const text=`${m.subject} ${m.body} ${m.stage||''}`.toLowerCase();if(text.match(/refund|dispute|angry|complaint|unsafe|legal|chargeback|sick|spoiled|threat/))return 'escalate';if(m.status==='failed')return 'failed';if(m.status==='received')return 'reply';if(m.status==='queued'||m.status==='draft')return 'pending';return 'normal'}
function short(value:string,n=140){return value&&value.length>n?`${value.slice(0,n)}...`:value}

export default function OwnerMessageBoard(){
  const [records,setRecords]=useState<Msg[]>([]);
  const [status,setStatus]=useState('Loading messages...');
  const [filter,setFilter]=useState('all');
  async function load(){setStatus('Loading messages...');const data=await fetch('/api/email-system',{credentials:'same-origin'}).then(r=>r.json()).catch(()=>null);if(data?.ok){setRecords(data.records||[]);setStatus(data.storage==='postgres'?'Live message records loaded.':'Memory message records loaded.')}else setStatus(data?.message||'Message records unavailable.');}
  useEffect(()=>{load()},[]);
  const stats=useMemo(()=>{const base={total:records.length,draft:0,queued:0,sent:0,received:0,failed:0,archived:0,followUp:0,escalate:0};for(const m of records){(base as any)[m.status]=((base as any)[m.status]||0)+1;const r=risk(m);if(['pending','reply','failed'].includes(r))base.followUp+=1;if(r==='escalate')base.escalate+=1}return base},[records]);
  const shown=records.filter(m=>filter==='all'||m.status===filter||risk(m)===filter);
  return <section className="section" id="owner-message-board"><div className="owner-board-head"><div><p className="eyebrow">Owner Message Board</p><h2>Every customer message in one control room.</h2><p>Drafts, queued Gmail opens, owner-confirmed sends, imported replies, failures, and escalations stay visible here.</p></div><button type="button" onClick={load}>Refresh</button></div><div className="route-list ops-cards owner-summary"><article><p className="eyebrow">Total</p><h3>{stats.total}</h3><p>All tracked messages.</p></article><article><p className="eyebrow">Queued</p><h3>{stats.queued}</h3><p>Opened or ready for Gmail send.</p></article><article><p className="eyebrow">Replies</p><h3>{stats.received}</h3><p>Imported customer responses.</p></article><article><p className="eyebrow">Needs follow-up</p><h3>{stats.followUp}</h3><p>Draft, queued, failed, or replied.</p></article><article><p className="eyebrow">Escalations</p><h3>{stats.escalate}</h3><p>Refund, complaint, safety, or dispute language.</p></article></div><div className="hero-actions"><button type="button" onClick={()=>setFilter('all')}>All</button><button type="button" onClick={()=>setFilter('queued')}>Queued</button><button type="button" onClick={()=>setFilter('sent')}>Sent</button><button type="button" onClick={()=>setFilter('received')}>Replies</button><button type="button" onClick={()=>setFilter('pending')}>Needs Follow-Up</button><button type="button" onClick={()=>setFilter('escalate')}>Escalations</button></div><p className="sales-save-notice">{status}</p>{shown.length?<div className="route-list ops-cards">{shown.map(m=><article key={m.id}><p className="eyebrow">{m.direction} · {m.status} · {risk(m)}</p><h3>{m.subject}</h3><p><strong>{m.customerName||'Customer'}</strong> {m.customerEmail}</p><p>{short(m.body)}</p><p>Source: {m.source||'unknown'} · Provider: {m.provider||'manual'} · Stage: {m.stage||'none'}</p></article>)}</div>:<article className="marble"><h3>No messages found.</h3><p>New drafts, queued messages, confirmations, and imported replies will appear here.</p></article>}</section>
}
