'use client';
import {displayContextTrust} from '../lib/context-trust';

type InboxProps={memory:Record<string,any>;orders:any[];turnIns:any[]};
function title(item:any){return item.subject||item.customer||item.customerName||item.leadName||item.driver||item.routeId||item.id||'Needs review'}
function detail(item:any){return item.body||item.note||item.customerNotes||item.ownerFollowup||item.partialReason||item.restockIssue||item.status||item.need||'Confirm this before treating it as official.'}
function action(item:any){const text=`${item.status||''} ${item.body||''} ${item.customerNotes||''} ${item.note||''}`.toLowerCase();if(text.includes('payment'))return 'Confirm payment and update invoice.';if(text.includes('reschedule')||text.includes('missed'))return 'Confirm timing and reschedule stop.';if(text.includes('partial')||text.includes('substitution'))return 'Confirm fulfillment issue before promising delivery.';if(text.includes('restock'))return 'Check inventory and restock plan.';if(item.contextTrust?.source==='customer-message')return 'Reply or confirm customer request.';if(item.contextTrust?.source==='driver-note')return 'Review driver note and assign owner follow-up.';return 'Confirm, reject, or convert to Owner Decision.'}
function isReview(item:any){const trust=item?.contextTrust;const status=String(item?.status||'').toLowerCase();return trust?.truthLevel==='pending-review'||trust?.truthLevel==='inferred'||trust?.source==='customer-message'||trust?.source==='driver-note'||trust?.source==='ai-summary'||['requested','review','reschedule-needed','partial','failed','disputed'].some(flag=>status.includes(flag))||Boolean(item?.missed||item?.rescheduled||item?.partialReason||item?.restockIssue)}
export function ownerReviewItems(memory:Record<string,any>,orders:any[],turnIns:any[]){const messages=[...(memory.records||[]),...(memory.messages||[]),...(memory.emailRecords||[]),...(memory.customerMessages||[])];const board=[...(memory.boardNotes||[]),...(memory.internalBoard||[]),...(memory.notes||[])];const insights=[...(memory.salesPriorities||[]),...(memory.restockRisks||[]),...(memory.operatorBrain?.salesPriorities||[]),...(memory.operatorBrain?.restockRisks||[])];return [...turnIns,...messages,...board,...insights,...orders].filter(isReview).slice(0,10)}
export default function OwnerNeedsReviewInbox({memory,orders,turnIns}:InboxProps){const items=ownerReviewItems(memory,orders,turnIns);return <section className="section" id="needs-review"><p className="eyebrow">Owner Needs Review</p><h2>Confirm before it becomes official.</h2><p>AI can use these items for context, but they need owner confirmation before customer promises or operational changes.</p><div className="review-board">{items.length?items.map((item:any,index:number)=><article className="review-card" key={item.id||`${title(item)}-${index}`}><small>{displayContextTrust(item.contextTrust)}</small><h3>{title(item)}</h3><p>{detail(item)}</p><strong>{action(item)}</strong></article>):<article className="review-card"><small>Confirmed · Official Records</small><h3>No pending review items.</h3><p>Driver notes, customer replies, AI insights, reschedule requests, partial deliveries, and restock risks will appear here when they need owner attention.</p><strong>Keep running the day from confirmed records.</strong></article>}</div><style>{`.review-board{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;margin-top:18px}.review-card{border:1px solid rgba(248,231,176,.28);border-radius:22px;background:linear-gradient(180deg,#100904,#050403);padding:16px}.review-card small{color:#d4af37;font-weight:800}.review-card h3{margin:8px 0;color:#f8e7b0}.review-card p{color:#ded2bd}.review-card strong{display:block;color:#fff7ed;margin-top:10px}`}</style></section>}
