'use client';
import {useMemo,useState} from 'react';

type Props={snapshot:Record<string,any>;sample:Record<string,any>};
type View='live'|'sample';
type Filter='all'|'hot'|'wholesale'|'waitlist'|'restock';

function money(value:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value||0)}
function downloadFile(name:string,type:string,content:string){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
function csvEscape(value:any){return `"${String(value??'').replace(/"/g,'""')}"`}
function csvExport(rows:any[]){const headers=['id','customerName','phone','zip','routeId','box','status','fulfillment','value','deliveryDate','deliveryWindow','notes','priority'];const lines=[headers.join(','),...rows.map(row=>headers.map(header=>csvEscape(row[header])).join(','))];downloadFile('ccp-owner-leads-orders.csv','text/csv',lines.join('\n')+'\n')}
function routeName(routeId:string,routes:any[]){return routes.find(route=>route.id===routeId)?.name||routeId||'Unassigned'}
function normalizeOrders(snapshot:Record<string,any>){return (snapshot.orderLifecycle||snapshot.orders||[]).map((order:any)=>({...order,priority:priorityFor(order),routeName:routeName(order.routeId,snapshot.routes||[])}))}
function priorityFor(order:any){const text=`${order.box||''} ${order.notes||''} ${order.status||''} ${order.fulfillment||''}`.toLowerCase();if(text.includes('wholesale'))return 'wholesale';if(text.includes('restock')||text.includes('partial')||text.includes('issue'))return 'restock';if(text.includes('waitlist')||text.includes('quoted'))return 'waitlist';if(Number(order.value||0)>=700)return 'hot';return 'normal'}
function filterOrders(orders:any[],filter:Filter){if(filter==='all')return orders;if(filter==='hot')return orders.filter(order=>order.priority==='hot'||Number(order.value||0)>=700);if(filter==='wholesale')return orders.filter(order=>order.priority==='wholesale');if(filter==='waitlist')return orders.filter(order=>order.priority==='waitlist'||order.status==='quoted');if(filter==='restock')return orders.filter(order=>order.priority==='restock'||order.fulfillment==='partial'||order.fulfillment==='restock-blocked');return orders}

export default function OwnerLeadDashboard({snapshot,sample}:Props){
  const [view,setView]=useState<View>('live');
  const [filter,setFilter]=useState<Filter>('all');
  const active=view==='live'?snapshot:sample;
  const orders=useMemo(()=>normalizeOrders(active),[active]);
  const visible=useMemo(()=>filterOrders(orders,filter),[orders,filter]);
  const report=active.ownerReport||{};
  const routes=active.routes||[];
  const counts={all:orders.length,hot:filterOrders(orders,'hot').length,wholesale:filterOrders(orders,'wholesale').length,waitlist:filterOrders(orders,'waitlist').length,restock:filterOrders(orders,'restock').length};
  const emptyLive=view==='live'&&!orders.length;

  return <section className="section owner-lead-dashboard" id="owner-leads">
    <div className="owner-board-head"><div><p className="eyebrow">Owner Lead Board</p><h2>Route demand, priority leads, and follow-up.</h2></div><div className="owner-view-toggle"><button onClick={()=>setView('live')} className={view==='live'?'active':''}>Live</button><button onClick={()=>setView('sample')} className={view==='sample'?'active':''}>Sample</button></div></div>
    <div className="owner-metrics"><article><span>Revenue</span><strong>{money(report.revenue)}</strong></article><article><span>Profit</span><strong>{money(report.estimatedProfit)}</strong></article><article><span>Open</span><strong>{report.openOrders||orders.length}</strong></article><article><span>Restock</span><strong>{report.restockIssues||counts.restock}</strong></article><article><span>Training</span><strong>{active.trainingDataset?.records?.length||0}</strong></article></div>
    <div className="owner-filters"><button onClick={()=>setFilter('all')} className={filter==='all'?'active':''}>All <b>{counts.all}</b></button><button onClick={()=>setFilter('hot')} className={filter==='hot'?'active':''}>Hot <b>{counts.hot}</b></button><button onClick={()=>setFilter('wholesale')} className={filter==='wholesale'?'active':''}>Wholesale <b>{counts.wholesale}</b></button><button onClick={()=>setFilter('waitlist')} className={filter==='waitlist'?'active':''}>Waitlist <b>{counts.waitlist}</b></button><button onClick={()=>setFilter('restock')} className={filter==='restock'?'active':''}>Restock <b>{counts.restock}</b></button><button onClick={()=>csvExport(visible)} disabled={!visible.length}>Export</button></div>
    {emptyLive?<article className="owner-empty marble"><h3>Live board is ready.</h3><p>No real intake has been created yet. Use Sample mode to rehearse follow-up, route grouping, exports, and AI learning approval without mixing demo data into live records.</p><a href="/system-database/sample">Open Sample Database</a></article>:<div className="owner-board-grid"><div className="lead-list">{visible.map((order:any)=><article key={order.id} className={`lead-row ${order.priority}`}><div><p className="eyebrow">{order.priority}</p><h3>{order.customerName||order.customer}</h3><p>{order.box} - {routeName(order.routeId,routes)}</p><small>{order.zip} - {order.phone}</small></div><div><strong>{money(order.value)}</strong><span>{order.status} / {order.fulfillment}</span><small>{order.deliveryDate} {order.deliveryWindow}</small></div><p>{order.notes||'No note yet.'}</p></article>)}</div><aside className="route-demand"><p className="eyebrow">Route Demand</p>{routes.map((route:any)=><article key={route.id}><h3>{route.name}</h3><p>{route.day} - {route.window}</p><div className="route-fill"><i style={{width:`${route.fill||Math.round(((route.reserved||0)/(route.capacity||1))*100)}%`}}/></div><small>{route.reserved}/{route.capacity} grouped - {route.status}</small></article>)}</aside></div>}
    <style>{`.owner-lead-dashboard{display:grid;gap:18px}.owner-board-head{display:flex;justify-content:space-between;gap:16px;align-items:end}.owner-board-head h2{margin:0}.owner-view-toggle,.owner-filters{display:flex;flex-wrap:wrap;gap:8px}.owner-view-toggle button,.owner-filters button,.owner-empty a{border:1px solid #d4af37;background:#080605;color:#f8e7b0;border-radius:999px;padding:10px 13px;font-weight:900}.owner-view-toggle button.active,.owner-filters button.active,.owner-empty a{background:linear-gradient(135deg,#facc15,#a16207);color:#160b04;border-color:#f8e7b0}.owner-filters button:disabled{opacity:.55}.owner-filters b{margin-left:4px}.owner-metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.owner-metrics article{border:1px solid #b8892d66;border-radius:16px;background:#080605;padding:14px}.owner-metrics span{display:block;color:#ded2bd;font-weight:800}.owner-metrics strong{display:block;color:#f8e7b0;font-size:1.45rem;margin-top:6px}.owner-board-grid{display:grid;grid-template-columns:1fr 320px;gap:18px}.lead-list{display:grid;gap:10px}.lead-row{display:grid;grid-template-columns:1.2fr .7fr 1fr;gap:14px;border:1px solid #b8892d66;border-radius:18px;background:#070504;padding:14px}.lead-row h3,.route-demand h3{margin:0;color:#f8e7b0}.lead-row p{margin:4px 0!important}.lead-row small,.lead-row span,.route-demand small{display:block;color:#ded2bd}.lead-row.hot{border-color:#facc15}.lead-row.wholesale{border-color:#93c5fd}.lead-row.restock{border-color:#fca5a5}.route-demand{display:grid;gap:10px;border:1px solid #b8892d66;border-radius:18px;background:#080605;padding:16px;height:max-content}.route-demand article{border-top:1px solid #b8892d44;padding-top:10px}.route-fill{height:9px;border:1px solid #b8892d66;border-radius:999px;background:#050403;overflow:hidden;margin:8px 0}.route-fill i{display:block;height:100%;max-width:100%;background:linear-gradient(90deg,#facc15,#ef4444)}.owner-empty{display:grid;gap:10px}.owner-empty h3{margin:0;color:#f8e7b0}@media(max-width:900px){.owner-board-head{display:grid}.owner-metrics{grid-template-columns:repeat(2,1fr)}.owner-board-grid{grid-template-columns:1fr}.lead-row{grid-template-columns:1fr}.route-demand{order:-1}}`}</style>
  </section>
}
