'use client';
import {useState,type FormEvent} from 'react';
import {saveAiExchange,type AiMemoryRole} from '../lib/ai-memory-client';
import {explainTruthLevel,type ContextTrust} from '../lib/context-trust';

type Msg={role:'user'|'assistant';content:string};
type PersistentChatBoxProps={role:AiMemoryRole;title:string;context?:Record<string,any>};
type ContextSummary={source:string;status:string;orders:number;routes:number;turnIns:number;permissions:string[];trust?:ContextTrust};
function summarizeContext(context?:Record<string,any>):ContextSummary{const memory=context?.memory||{};const orders=Array.isArray(memory.orders)?memory.orders:Array.isArray(memory.orderLifecycle)?memory.orderLifecycle:[];const routes=Array.isArray(memory.routes)?memory.routes:[];const turnIns=Array.isArray(memory.turnIns)?memory.turnIns:[];const role=String(context?.role||'');const permissionList=context?.permissions?.[role];return {source:String(context?.contextSource||'page context'),status:String(context?.contextStatus||''),orders:orders.length,routes:routes.length,turnIns:turnIns.length,permissions:Array.isArray(permissionList)?permissionList.map(String):[],trust:context?.contextTrust}}
function trustLine(summary:ContextSummary){const trust=summary.trust;if(!trust)return 'This context is unlabeled, so verify before action.';return `${trust.truthLevel} ${trust.source} context at ${Math.round((trust.confidence||0)*100)}% confidence. ${explainTruthLevel(trust)}`}
function answer(role:AiMemoryRole,text:string,context?:Record<string,any>){const q=text.toLowerCase();const summary=summarizeContext(context);const truth=trustLine(summary);if(role==='owner'){if(q.includes('today'))return `Start with messages, routes, revenue, restock risk, and driver follow-up. This workspace sees ${summary.orders} order(s), ${summary.routes} route(s), and ${summary.turnIns} turn-in(s). ${truth}`;if(q.includes('context')||q.includes('memory')||q.includes('truth'))return `Owner context is connected from ${summary.source}. ${summary.status||'No extra status message.'} ${truth}`;return `Owner AI memory saved this exchange for operational review. ${truth}`}if(role==='driver'){if(q.includes('route'))return `Check assigned stops, message needs, delivery notes, restock flags, fuel, and turn-in before closeout. This workspace sees ${summary.routes} route(s) and ${summary.orders} order(s). ${truth}`;if(q.includes('context')||q.includes('memory')||q.includes('truth'))return `Driver context is connected from ${summary.source}. ${summary.status||'No extra status message.'} ${truth}`;return `Driver AI memory saved this exchange for route review. ${truth}`}if(q.includes('delivery'))return `Share your ZIP so CCP can check route and timing. ${truth}`;if(q.includes('context')||q.includes('memory')||q.includes('truth'))return `Customer context is connected from ${summary.source}. ${truth}`;return `Customer AI memory saved this exchange for follow-up. ${truth}`}
export default function PersistentChatBox({role,title,context}:PersistentChatBoxProps){const [sessionId,setSessionId]=useState('');const [input,setInput]=useState('');const summary=summarizeContext(context);const [messages,setMessages]=useState<Msg[]>([{role:'assistant',content:`${title} is ready. ${trustLine(summary)}`}]);async function send(e?:FormEvent){e?.preventDefault();const question=input.trim();if(!question)return;const id=sessionId||`CHAT-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;if(!sessionId)setSessionId(id);const reply=answer(role,question,context);setMessages([...messages,{role:'user',content:question},{role:'assistant',content:reply}]);setInput('');await saveAiExchange({role,sessionId:id,title:question.split(' ').slice(0,8).join(' ')||title,subjectKey:role,messages:[{role:'system',content:trustLine(summary),metadata:{contextTrust:summary.trust||null}},{role:'user',content:question},{role:'assistant',content:reply}],context:{source:summary.source,status:summary.status,orders:summary.orders,routes:summary.routes,turnIns:summary.turnIns,permissions:summary.permissions,trust:summary.trust}})}return <section className="local-ai-panel"><div className="local-ai-head"><div><p className="eyebrow">Persistent AI</p><h3>{title}</h3><p>Every exchange is saved through the AI memory API when access allows it.</p><small>{summary.orders} orders · {summary.routes} routes · {summary.turnIns} turn-ins · {summary.trust?.truthLevel||'unlabeled'} · {summary.trust?.source||summary.source}</small></div></div><div className="local-ai-chat">{messages.map((m,i)=><div key={i} className={`ai-bubble ${m.role}`}>{m.content}</div>)}</div><form onSubmit={send} className="local-ai-input"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask and save to memory..."/><button type="submit">Ask</button></form>{sessionId&&<p className="sales-save-notice">Memory: {sessionId}</p>}</section>}
