'use client';
import {useEffect,useMemo,useState} from 'react';

type Lead=Record<string,any>;
function money(value:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value||0))}
function clean(value:unknown){return String(value||'').trim()}
function leadName(lead:Lead){return clean(lead.leadName||lead.customerName||lead.name)||'Unnamed lead'}
function leadEmail(lead:Lead){return clean(lead.email||lead.customerEmail)}
function leadValue(lead:Lead){return Number(lead.estimatedValue||lead.estimated_value||lead.value||0)||500}
function leadZip(lead:Lead){return clean(lead.zip||lead.deliveryZip)}
function leadScore(lead:Lead){const status=clean(lead.status);return (status==='reserved'?100:status==='pitched'?75:status==='queued'?50:10)+leadValue(lead)/25+(leadEmail(lead)?20:-30)}

export default function RevenuePipelineCenter(){
  const [leads,setLeads]=useState<Lead[]>([]);const [invoices,setInvoices]=useState<any[]>([]);const [appointments,setAppointments]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState('');const [selected,setSelected]=useState('');
  const selectedLead=leads.find(lead=>lead.id===selected)||leads[0];
  const sorted=useMemo(()=>[...leads].sort((a,b)=>leadScore(b)-leadScore(a)),[leads]);
  const invoicedIds=new Set(invoices.map(invoice=>invoice.metadata?.leadId).filter(Boolean));
  const appointmentInvoiceIds=new Set(appointments.map(appt=>appt.invoiceId||appt.invoice_id).filter(Boolean));
  async function load(){setLoading(true);try{const [salesRes,billingRes,apptRes]=await Promise.all([fetch('/api/ops/driver-sales',{credentials:'same-origin'}),fetch('/api/billing/invoices',{credentials:'same-origin'}),fetch('/api/scheduling/appointments',{credentials:'same-origin'})]);const sales=await salesRes.json();const billing=await billingRes.json();const appts=await apptRes.json();if(sales.ok)setLeads(sales.leads||[]);if(billing.ok)setInvoices(billing.invoices||[]);if(appts.ok)setAppointments(appts.appointments||[])}catch(error){setNotice('Pipeline could not load yet. Unlock owner access and try again.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function createInvoice(lead:Lead){
    if(!leadEmail(lead)){setNotice('This lead needs a customer email before invoice creation.');return}
    setNotice(`Creating invoice for ${leadName(lead)}...`);
    const payload={action:'create-invoice',invoice:{customerName:leadName(lead),customerEmail:leadEmail(lead),customerPhone:clean(lead.phone),deliveryZip:leadZip(lead),deliveryZoneStatus:clean(lead.deliveryZoneStatus),deliveryZoneRing:clean(lead.deliveryZoneRing),lineItems:[{description:clean(lead.offer||lead.need)||'Custom Freezer Box',qty:1,unitPrice:leadValue(lead),taxCategory:'grocery_food'}],notes:[clean(lead.note),`Lead source: ${clean(lead.sourceStopId||lead.sourceCustomer||'sales queue')}`,`ZIP: ${leadZip(lead)} ${clean(lead.deliveryZoneStatus)}`].filter(Boolean).join(' | '),metadata:{source:'lead-to-invoice-pipeline',leadId:lead.id,driver:lead.driver,routeId:lead.routeId,status:lead.status,temperature:lead.temperature}}};
    try{const response=await fetch('/api/billing/invoices',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'Invoice failed');setNotice(`Invoice ${data.invoice.invoiceNumber} queued for ${data.invoice.customerEmail}.`);await load()}catch(error:any){setNotice(error?.message||'Invoice failed. Confirm customer email and billing storage.')}}
  async function recordPayment(invoice:any){const amount=prompt('Amount received',String(invoice.balanceDue||invoice.total||0));if(!amount)return;const method=prompt('Payment method: cash, ach, zelle, check, btcpay, hosted-card','manual')||'manual';setNotice('Recording payment and creating receipt...');try{const response=await fetch('/api/billing/invoices',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'record-payment',invoiceId:invoice.id,amount:Number(amount),provider:method,method})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'Payment failed');setNotice(`Receipt ${data.receipt.receiptNumber} queued for ${data.invoice.customerEmail}.`);await load()}catch(error:any){setNotice(error?.message||'Payment failed.')}}
  async function scheduleInvoice(invoice:any){const confirmedDate=prompt('Confirmed delivery date, e.g. 2026-06-15','');const confirmedWindow=prompt('Confirmed delivery window, e.g. 3 PM - 6 PM','');if(!confirmedDate&&!confirmedWindow)return;setNotice('Creating delivery appointment confirmation...');try{const response=await fetch('/api/scheduling/appointments',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({appointment:{invoiceId:invoice.id,orderId:invoice.orderId,customerName:invoice.customerName,customerEmail:invoice.customerEmail,customerPhone:invoice.customerPhone,deliveryZip:invoice.deliveryZip,address:invoice.metadata?.address||'',routeId:invoice.metadata?.routeId||`route-${invoice.deliveryZip||'pending'}`,driver:invoice.metadata?.driver||'',requestedWindow:confirmedWindow||'Pending owner confirmation',confirmedDate,confirmedWindow,driverNotes:`Invoice ${invoice.invoiceNumber}. Balance ${money(invoice.balanceDue||0)}.`,customerNotes:invoice.notes,metadata:{source:'revenue-pipeline',invoiceNumber:invoice.invoiceNumber,total:invoice.total,balanceDue:invoice.balanceDue}}})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'Appointment failed');setNotice(`Appointment ${data.appointment.id} queued for ${data.appointment.customerEmail}.`);await load()}catch(error:any){setNotice(error?.message||'Appointment failed.')}}
  return <section className="section revenue-pipeline" id="revenue-pipeline">
    <div className="owner-board-head"><div><p className="eyebrow">Revenue Pipeline</p><h2>Cold knock to invoice to receipt to appointment.</h2><p>Turn field-sales leads into invoices, record payments, queue receipts, and confirm delivery appointments without leaving the owner workspace.</p></div><button onClick={load}>{loading?'Loading':'Refresh'}</button></div>
    <div className="sales-hero-board"><article><p className="eyebrow">Open Leads</p><h3>{leads.length}</h3><p>{sorted.filter(lead=>!invoicedIds.has(lead.id)).length} not invoiced yet.</p></article><article><p className="eyebrow">Open Invoice Value</p><h3>{money(invoices.reduce((sum,invoice)=>sum+Number(invoice.balanceDue||0),0))}</h3><p>Balance due across visible invoices.</p></article><article><p className="eyebrow">Appointments</p><h3>{appointments.length}</h3><p>{appointments.filter(appt=>appt.status==='confirmed').length} confirmed.</p></article></div>
    <div className="sales-work-grid"><div className="sales-lead-stack"><div className="stack-head"><div><p className="eyebrow">Sales Queue</p><h3>Pick a lead and move it forward.</h3></div></div>{sorted.length?sorted.map(lead=><article key={lead.id} onClick={()=>setSelected(lead.id)} className={selected===lead.id?'active':''}><div><span>{clean(lead.status)||'queued'}</span><h4>{leadName(lead)}</h4><p>{clean(lead.offer||lead.need)||'Freezer box follow-up'}</p><small>{leadEmail(lead)||'email required'} · ZIP {leadZip(lead)||'TBD'} · {clean(lead.deliveryZoneStatus)||'zone unknown'}</small></div><div><strong>{money(leadValue(lead))}</strong><small>{invoicedIds.has(lead.id)?'Invoice created':'Not invoiced'}</small></div><div className="queue-actions"><button onClick={event=>{event.stopPropagation();createInvoice(lead)}} disabled={!leadEmail(lead)||invoicedIds.has(lead.id)}>{invoicedIds.has(lead.id)?'Invoiced':'Create Invoice'}</button></div></article>):<article><h3>No sales leads yet.</h3><p>Use /field-sales or the driver sales route mode to capture real prospects.</p></article>}</div>
      <aside className="sales-ai-panel"><p className="eyebrow">Selected Lead</p><h3>{selectedLead?leadName(selectedLead):'No lead selected'}</h3>{selectedLead?<><p>{clean(selectedLead.note)||'No note yet.'}</p><div className="lead-brief"><span><b>{leadZip(selectedLead)||'TBD'}</b> ZIP</span><span><b>{clean(selectedLead.deliveryZoneStatus)||'unknown'}</b> zone</span><span><b>{money(leadValue(selectedLead))}</b> value</span></div><button onClick={()=>createInvoice(selectedLead)} disabled={!leadEmail(selectedLead)||invoicedIds.has(selectedLead.id)}>{leadEmail(selectedLead)?'Create Invoice From This Lead':'Email Required'}</button></>:<p>Capture or select a lead.</p>}{notice&&<p className="sales-save-notice">{notice}</p>}</aside></div>
    <section className="section"><p className="eyebrow">Billing & Appointment Follow-Up</p><h2>Move paid customers into confirmed delivery.</h2><div className="route-list ops-cards">{invoices.length?invoices.map(invoice=><article key={invoice.id}><p className="eyebrow">{invoice.status}</p><h3>{invoice.invoiceNumber}</h3><p>{invoice.customerName} · {invoice.customerEmail}</p><p>Total {money(invoice.total)} · Paid {money(invoice.amountPaid)} · Balance {money(invoice.balanceDue)}</p><div className="actions"><button onClick={()=>recordPayment(invoice)} disabled={Number(invoice.balanceDue||0)<=0}>{Number(invoice.balanceDue||0)<=0?'Paid':'Record Payment / Receipt'}</button><button onClick={()=>scheduleInvoice(invoice)} disabled={appointmentInvoiceIds.has(invoice.id)}>{appointmentInvoiceIds.has(invoice.id)?'Scheduled':'Schedule / Confirm'}</button></div></article>):<article><h3>No invoices yet.</h3><p>Create one from a sales lead to begin the billing chain.</p></article>}</div></section>
    <section className="section"><p className="eyebrow">Delivery Appointments</p><h2>Confirmed route promises.</h2><div className="route-list ops-cards">{appointments.length?appointments.map(appt=><article key={appt.id}><p className="eyebrow">{appt.status}</p><h3>{appt.customerName}</h3><p>{appt.customerEmail} · ZIP {appt.deliveryZip}</p><p>{appt.confirmedDate||'Date pending'} · {appt.confirmedWindow||appt.requestedWindow||'Window pending'}</p><p>{appt.confirmationEmailStatus||'email pending'}</p></article>):<article><h3>No appointments yet.</h3><p>After receipt/payment, use Schedule / Confirm from an invoice.</p></article>}</div></section>
  </section>
}
